version: 0.0

env:
  parameter-store:
    CONTAINER_NAME: /inflearn-lecture/container-name

Resources:
 - TargetService:
     Type: AWS::ECS::Service
     Properties:
       TaskDefinition: <TASK_DEFINITION>
       LoadBalancerInfo:
         ContainerName: $CONTAINER_NAME
         ContainerPort: 8000
