version: 0.2

env:
  parameter-store:
    ECR_REGION: /inflearn-lecture/ecr-region
    AWS_ACCOUNT_ID: /inflearn-lecture/aws-account-id 
    CONTAINER_NAME: /inflearn-lecture/container-name

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $ECR_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$ECR_REGION.amazonaws.com
  build:
    commands:
      - echo Building the Docker image...
      - docker build -t $AWS_ACCOUNT_ID.dkr.ecr.$ECR_REGION.amazonaws.com/$CONTAINER_NAME:latest .
  post_build:
    commands:
      - echo Pushing the Docker image...
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$ECR_REGION.amazonaws.com/$CONTAINER_NAME:latest
      - echo Writing image definitions file...
      - printf '[{"name": "%s","imageUri":"%s"}]' $CONTAINER_NAME $AWS_ACCOUNT_ID.dkr.ecr.$ECR_REGION.amazonaws.com/$CONTAINER_NAME:latest > imagedefinitions.json
artifacts:
  files:
    - imagedefinitions.json
    - taskdef.json
    - appspec.yml


